#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const path = require("node:path");
const c = require("./protocol.js");

const out = path.join(__dirname, "..", "editor-extension", "lib", "contract.js");
const body = `"use strict";

// Generated by contract/sync.js. Do not edit.
// Copied into the extension so the installed package can load it.

/** @type {import("./contract-types.js").ProtocolConstants} */
module.exports = ${JSON.stringify(
  { PROTOCOL_VERSION: c.PROTOCOL_VERSION, ERROR_CODES: c.ERROR_CODES, SIDES: c.SIDES, MODES: c.MODES, STOP_TYPES: c.STOP_TYPES },
  null,
  2
)};
`;

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, body);
console.log(`wrote ${out}`);

// Source-backed tour validation must behave identically in the MCP and VSIX.
const tourOut = path.join(path.dirname(out), "tour-contract.js");
fs.writeFileSync(tourOut, fs.readFileSync(path.join(__dirname, "tour.js")));
console.log(`wrote ${tourOut}`);
// Copy types alongside the JavaScript.
const typesOut = path.join(path.dirname(out), "contract-types.d.ts");
fs.writeFileSync(typesOut, fs.readFileSync(path.join(__dirname, "contract-types.d.ts")));
console.log(`wrote ${typesOut}`);
for (const name of ["tour-sources", "narration"]) {
  const source = fs.readFileSync(path.join(__dirname, `${name}.js`), "utf8").replace('require("./tour.js")', 'require("./tour-contract.js")');
  fs.writeFileSync(path.join(path.dirname(out), `${name}.js`), source);
}
