"use strict";

// Generated by contract/sync.js. Do not edit.
// The extension is packaged as a .vsix and cannot require outside its own
// directory, so the shared contract is copied here and drift-checked in CI.

/** @type {import("./contract-types.js").ProtocolConstants} */
module.exports = {
  "PROTOCOL_VERSION": 3,
  "ERROR_CODES": [
    "unauthorized",
    "protocol_mismatch",
    "bad_request",
    "file_not_found",
    "range_out_of_bounds",
    "git_failed",
    "no_active_editor",
    "content_drift",
    "diff_identity_mismatch",
    "invalid_tour_plan",
    "no_tour",
    "stale_presentation",
    "navigation_boundary"
  ],
  "SIDES": [
    "base",
    "head",
    "working"
  ],
  "MODES": [
    "diff",
    "file"
  ],
  "STOP_TYPES": [
    "context",
    "implementation",
    "risk",
    "evidence",
    "limitation"
  ]
};
